package Bank.Cards;

import java.util.concurrent.ThreadLocalRandom;

public abstract class Card {
    public enum CardTypes {PLATINUMCARD, TITANIUMCARD, MASTERCARD}
    private CardTypes cardType;
    private long cardNumber;
    private String hashedCode;
    private double withdrawLimit;
    private double transferLimit;
    private double depositLimit;
    private double transferLimitOwnAccount;
    private double depositLimitOwnAccount;
    private double amountWithdrawnToday;
    private double transferredWithdrawnToday;
    private double amountTransferredToOwnAccountToday;
    private double amountDepositedToday;
    private double amountDepositedToOwnAccountToday;

    public Card(String hashedCode, CardTypes cardType, double withdrawLimit, double transferLimit, double depositLimit, double transferLimitOwnAccount, double depositLimitOwnAccount) {
        cardNumber = generateRandom12DigitCardNumber(); // this is currently not unique. fix later when db is implemented;
        this.hashedCode = hashedCode;
        this.cardType = cardType;
        this.withdrawLimit = withdrawLimit;
        this.transferLimit = transferLimit;
        this.depositLimit = depositLimit;
        this.transferLimitOwnAccount = transferLimitOwnAccount;
        this.depositLimitOwnAccount = depositLimitOwnAccount;
        amountWithdrawnToday = 0;
        transferredWithdrawnToday = 0;
        amountTransferredToOwnAccountToday = 0;
        amountDepositedToday = 0;
        amountDepositedToOwnAccountToday = 0;
    }

    /*
    =============================================================================
    Setters and getters
    =============================================================================
     */

    public long getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(long cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getHashedCode() {
        return hashedCode;
    }

    public void setHashedCode(String hashedCode) {
        this.hashedCode = hashedCode;
    }

    public double getWithdrawLimit() {
        return withdrawLimit;
    }

    public void setWithdrawLimit(double withdrawLimit) {
        this.withdrawLimit = withdrawLimit;
    }

    public double getTransferLimit() {
        return transferLimit;
    }

    public void setTransferLimit(double transferLimit) {
        this.transferLimit = transferLimit;
    }

    public double getDepositLimit() {
        return depositLimit;
    }

    public void setDepositLimit(double depositLimit) {
        this.depositLimit = depositLimit;
    }

    public double getTransferLimitOwnAccount() {
        return transferLimitOwnAccount;
    }

    public void setTransferLimitOwnAccount(double transferLimitOwnAccount) {
        this.transferLimitOwnAccount = transferLimitOwnAccount;
    }

    public double getDepositLimitOwnAccount() {
        return depositLimitOwnAccount;
    }

    public void setDepositLimitOwnAccount(double depositLimitOwnAccount) {
        this.depositLimitOwnAccount = depositLimitOwnAccount;
    }

    public double getAmountWithdrawnToday() {
        return amountWithdrawnToday;
    }

    public void setAmountWithdrawnToday(double amountWithdrawnToday) {
        this.amountWithdrawnToday = amountWithdrawnToday;
    }

    public double getTransferredWithdrawnToday() {
        return transferredWithdrawnToday;
    }

    public void setTransferredWithdrawnToday(double transferredWithdrawnToday) {
        this.transferredWithdrawnToday = transferredWithdrawnToday;
    }

    public double getAmountTransferredToOwnAccountToday() {
        return amountTransferredToOwnAccountToday;
    }

    public void setAmountTransferredToOwnAccountToday(double amountTransferredToOwnAccountToday) {
        this.amountTransferredToOwnAccountToday = amountTransferredToOwnAccountToday;
    }

    public double getAmountDepositedToday() {
        return amountDepositedToday;
    }

    public void setAmountDepositedToday(double amountDepositedToday) {
        this.amountDepositedToday = amountDepositedToday;
    }

    public double getAmountDepositedToOwnAccountToday() {
        return amountDepositedToOwnAccountToday;
    }

    public void setAmountDepositedToOwnAccountToday(double amountDepositedToOwnAccountToday) {
        this.amountDepositedToOwnAccountToday = amountDepositedToOwnAccountToday;
    }

    /*
    =============================================================================
    Methods
    =============================================================================
     */

    // this method is generated by copilot gemini
    // what I should do next is create a method that takes in this number and checks if its already been handed
    // save used cards numbers in some file
    public static long generateRandom12DigitCardNumber() {
        long min = 1_000_000_000_000_000L;
        long max = 9_999_999_999_999_999L;
        long random16DigitNumber = ThreadLocalRandom.current().nextLong(min, max + 1);
        System.out.println("Random 12-Digit Number: " + random16DigitNumber);
        return random16DigitNumber;
    }
}
